# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\github\bbc_english_test\UI\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 428)
        self.Login = QtWidgets.QPushButton(Dialog)
        self.Login.setEnabled(True)
        self.Login.setGeometry(QtCore.QRect(160, 350, 75, 23))
        self.Login.setObjectName("Login")
        self.Password = QtWidgets.QLineEdit(Dialog)
        self.Password.setGeometry(QtCore.QRect(130, 230, 161, 20))
        self.Password.setObjectName("Password")
        self.ID = QtWidgets.QLineEdit(Dialog)
        self.ID.setGeometry(QtCore.QRect(130, 160, 161, 20))
        self.ID.setObjectName("ID")
        self.Username_label = QtWidgets.QLabel(Dialog)
        self.Username_label.setGeometry(QtCore.QRect(130, 130, 161, 20))
        self.Username_label.setScaledContents(False)
        self.Username_label.setObjectName("Username_label")
        self.Password_label = QtWidgets.QLabel(Dialog)
        self.Password_label.setGeometry(QtCore.QRect(130, 200, 161, 20))
        self.Password_label.setScaledContents(False)
        self.Password_label.setObjectName("Password_label")
        self.Main_label = QtWidgets.QLabel(Dialog)
        self.Main_label.setGeometry(QtCore.QRect(80, 60, 261, 20))
        self.Main_label.setObjectName("Main_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Login.setText(_translate("Dialog", "PushButton"))
        self.Username_label.setText(_translate("Dialog", "Username"))
        self.Password_label.setText(_translate("Dialog", "Password"))
        self.Main_label.setText(_translate(
            "Dialog", "Log in your account to proceed"))
